# Qlib 配置文件
qlib_init:
  provider_uri: "~/.qlib/qlib_data/cn_data"
  region: "cn"
  dataset_cache: null
  auto_mount: true
  exp_manager:
    class: "MLflowExpManager"
    module_path: "qlib.workflow.expm"
    kwargs:
      uri: "file://mlruns"
      default_exp_name: "qlib_experiment"

# 市场配置
market: "csi300"
benchmark: "SH000300"

# 数据处理器配置
data_handler_config:
  start_time: "2018-01-01"
  end_time: "2023-12-31"
  fit_start_time: "2018-01-01"
  fit_end_time: "2020-12-31"
  instruments: "csi300"
  infer_processors:
    - class: "RobustZScoreNorm"
      kwargs:
        fields_group: "feature"
        clip_outlier: true
    - class: "Fillna"
      kwargs:
        fields_group: "feature"
  learn_processors:
    - class: "DropnaLabel"
    - class: "CSRankNorm"
      kwargs:
        fields_group: "label"

# 数据集配置
dataset:
  class: "DatasetH"
  module_path: "qlib.data.dataset"
  kwargs:
    handler:
      class: "Alpha158"
      module_path: "qlib.contrib.data.handler"
      kwargs: {}
    segments:
      train: ["2018-01-01", "2020-12-31"]
      valid: ["2021-01-01", "2021-12-31"] 
      test: ["2022-01-01", "2023-12-31"]

# 模型配置
model:
  class: "LGBModel"
  module_path: "qlib.contrib.model.gbdt"
  kwargs:
    loss: "mse"
    colsample_bytree: 0.8879
    learning_rate: 0.0421
    subsample: 0.8789
    lambda_l1: 205.6999
    lambda_l2: 580.9768
    max_depth: 8
    num_leaves: 210
    num_threads: 20

# 策略配置  
strategy:
  class: "TopkDropoutStrategy"
  module_path: "qlib.contrib.strategy.signal_strategy"
  kwargs:
    signal: "<PRED>"
    topk: 50
    n_drop: 5

# 回测配置
backtest:
  start_time: "2022-01-01"
  end_time: "2023-12-31"
  account: 100000000
  benchmark: "SH000300"
  exchange_kwargs:
    freq: "day"
    limit_threshold: 0.095
    deal_price: "close"
    open_cost: 0.0005
    close_cost: 0.0015
    trade_unit: 100

# 组合分析配置
port_analysis_config:
  strategy:
    class: "TopkDropoutStrategy"
    module_path: "qlib.contrib.strategy.signal_strategy"
    kwargs:
      signal: "<PRED>"
      topk: 50
      n_drop: 5
  backtest:
    start_time: "2022-01-01"
    end_time: "2023-12-31"
    account: 100000000
    benchmark: "SH000300"
    exchange_kwargs:
      freq: "day"
      limit_threshold: 0.095
      deal_price: "close"
      open_cost: 0.0005
      close_cost: 0.0015
      trade_unit: 100

# 任务配置
task:
  model: 
    class: "LGBModel"
    module_path: "qlib.contrib.model.gbdt"
    kwargs:
      loss: "mse"
      colsample_bytree: 0.8879
      learning_rate: 0.0421
      subsample: 0.8789
      lambda_l1: 205.6999
      lambda_l2: 580.9768
      max_depth: 8
      num_leaves: 210
      num_threads: 20
  dataset:
    class: "DatasetH"
    module_path: "qlib.data.dataset"
    kwargs:
      handler:
        class: "Alpha158"
        module_path: "qlib.contrib.data.handler"
      segments:
        train: ["2018-01-01", "2020-12-31"]
        valid: ["2021-01-01", "2021-12-31"]
        test: ["2022-01-01", "2023-12-31"]
  record:
    - class: "SignalRecord"
      module_path: "qlib.workflow.record_temp"
      kwargs: {}
    - class: "SigAnaRecord" 
      module_path: "qlib.workflow.record_temp"
      kwargs:
        ana_long_short: false
        ann_scaler: 252
    - class: "PortAnaRecord"
      module_path: "qlib.workflow.record_temp"
      kwargs:
        config: *port_analysis_config