# ===============================================
# Qlib 完整工作流配置文件
# ===============================================
# 该文件可直接用于 `qrun` 命令执行一个完整的量化研究流程

# -------------------------------------------
# 步骤 1: 基础设置
# -------------------------------------------
qlib_init:
    provider_uri: ~/.qlib/qlib_data/cn_data # 数据存放路径，请确保已初始化
    region: cn

market: csi300         # 股票池：使用沪深300成分股
benchmark: SH000300   # 业绩基准：沪深300指数

# -------------------------------------------
# 步骤 2: 数据处理与因子工程
# -------------------------------------------
data_handler_config:
    start_time: 2010-01-01
    end_time: 2020-12-31
    fit_start_time: 2010-01-01 # 因子预处理（如标准化）的拟合开始时间
    fit_end_time: 2017-12-31   # 因子预处理（如标准化）的拟合结束时间
    instruments: market       # 使用上面定义的market(csi300)作为股票池

    # 标签定义 (预测目标 Y)
    # Ref($close, -1) 表示获取明天的收盘价
    # 整体公式为：(明天的收盘价 / 今天的收盘价) - 1
    label: ["Ref($close, -1) / $close - 1"]

# -------------------------------------------
# 步骤 3: 模型训练任务
# -------------------------------------------
task:
    # 模型定义
    model:
        class: LightGBM
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: mse
            n_estimators: 200
            seed: 2024 # 设置随机种子以保证结果可复现

    # 数据集定义
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            # 处理器：定义如何生成因子和标签
            handler:
                class: Alpha158  # 使用内置的 Alpha158 因子库作为特征 X
                module_path: qlib.contrib.data.handler
                kwargs: {} # 使用默认参数
            
            # 数据集时间划分
            segments:
                train: [2010-01-01, 2017-12-31] # 训练集
                valid: [2018-01-01, 2018-12-31] # 验证集
                test: [2019-01-01, 2020-12-31]  # 测试集

# -------------------------------------------
# 步骤 4: 策略回测
# -------------------------------------------
port_analysis_config:
    # 策略定义
    strategy:
        class: TopkDropoutStrategy # 经典的Top-K选股策略
        module_path: qlib.contrib.strategy
        kwargs:
            topk: 50    # 每期选择模型预测分数最高的50只股票
            n_drop: 5   # 每期淘汰持仓中排名最低的5只股票

    # 回测参数
    backtest:
        start_time: 2019-01-01 # 回测开始时间，应与测试集(test)的开始时间对应
        end_time: 2020-12-31   # 回测结束时间，应与测试集(test)的结束时间对应
        account: 100000000     # 初始资金
        benchmark: SH000300    # 业绩基准
        exchange_kwargs:
            limit_threshold: 0.095 # 涨跌停限制
            deal_price: close      # 以收盘价成交
            open_cost: 0.0005      # 开仓手续费率
            close_cost: 0.0015     # 平仓手续费率
            min_cost: 5            # 最低手续费
